// Re-export from library for backward compatibility
export {
  useArtists,
  useCategories,
  useProducts,
  useInstructors,
  useHopeQueue,
  useNeedsAttention,
  useLessonInquiries,
  useStudents,
  useLessons,
  useLessonBlocks,
  useInvoices,
  useTeacherPayouts,
  useClasses,
  useClassCategories,
  useDiscounts,
  useRegistrations,
  useClassWaitlist,
  useClassWaitlistCounts,
  useCalendarEvents,
  useArtistPayouts,
  useAgreementTemplates,
  useAgreementRequests,
  useSignedAgreement,
  useUsers,
  useSales,
  useEtsyPush,
  useCraftClubMembers,
  useMusicTogetherSections,
  useMusicTogetherSemesters,
  useMusicTogetherRoster,
  useMusicTogetherInterest,
  useMusicTogetherDemos,
  useMusicTogetherDemoRsvps,
} from '@maple/react/data';
export { useAuth } from '@maple/react/auth';
