name: Bug Report
description: Report a bug or issue
title: "fix: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please describe the bug you encountered.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: testing-requirements
    attributes:
      label: Testing Requirements
      description: What tests should be added to prevent regression?
      value: |
        - [ ] Add test that reproduces the bug (should fail before fix)
        - [ ] Verify test passes after fix
        - [ ] All existing tests pass (`npm test`)
    validations:
      required: true
