/**
 * OAuth 2.0 types for Etsy API authentication
 *
 * Etsy uses OAuth 2.0 Authorization Code Grant with mandatory PKCE (S256).
 * Access tokens expire in 1 hour; refresh tokens expire in 90 days.
 *
 * @see https://developers.etsy.com/documentation/essentials/authentication/
 */

/**
 * Stored OAuth token data.
 *
 * Storage is pluggable via the TokenStorage interface — the Etsy client
 * does not depend on any specific persistence layer.
 */
export interface TokenData {
  accessToken: string;
  refreshToken: string;
  /** Unix timestamp in milliseconds when the access token expires */
  expiresAt: number;
  /** Etsy shop ID (extracted from token response) */
  shopId: string;
  /** Etsy user ID (extracted from token prefix) */
  userId: string;
}

/**
 * Pluggable token persistence interface.
 *
 * Implement this to store tokens in Firestore, a file, memory, or any
 * other backend. The Etsy client calls these methods to read and write
 * tokens during normal operation and token refresh.
 */
export interface TokenStorage {
  getTokens(): Promise<TokenData | null>;
  saveTokens(tokens: TokenData): Promise<void>;
}

/**
 * Configuration for the EtsyClient.
 */
export interface EtsyClientConfig {
  /** Etsy API keystring (from developer dashboard) */
  apiKey: string;
  /** Etsy shared secret (required since Jan 2026) */
  sharedSecret: string;
  /** Pluggable token storage implementation */
  tokenStorage: TokenStorage;
  /** OAuth redirect URI (only needed for the authorization flow) */
  redirectUri?: string;
}

/**
 * Parameters for generating an OAuth authorization URL.
 */
export interface AuthUrlParams {
  /** OAuth scopes to request (space-separated) */
  scopes: string;
  /** The code verifier generated by PKCE — store this to use during token exchange */
  codeVerifier: string;
  /** The code challenge derived from the verifier */
  codeChallenge: string;
  /** Random state string for CSRF protection */
  state: string;
}

/**
 * Result of generating an OAuth authorization URL.
 */
export interface AuthUrlResult {
  /** Full authorization URL to redirect the user to */
  url: string;
  /** Code verifier — must be stored and sent during token exchange */
  codeVerifier: string;
  /** State parameter — must be validated on callback */
  state: string;
}

/**
 * Parameters for exchanging an authorization code for tokens.
 */
export interface TokenExchangeParams {
  /** Authorization code received from Etsy callback */
  code: string;
  /** Code verifier that was generated with the authorization URL */
  codeVerifier: string;
}

/**
 * Raw token response from Etsy's OAuth endpoint.
 */
export interface EtsyTokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
  refresh_token: string;
}
