#!/usr/bin/env bash
#
# Bootstrap a git worktree for parallel development.
#
# Does two things:
#   1. Derives a deterministic EMULATOR_PORT_OFFSET from the branch name so
#      emulators/mock-server/test runs in this worktree never collide with
#      the main checkout or another worktree.
#   2. Writes .env.worktree (gitignored) with that offset + NX_DAEMON=false.
#      Source it in your shell before running dev/test commands.
#
# Usage:
#   ./tools/bootstrap-worktree.sh                    # env only
#   ./tools/bootstrap-worktree.sh --link-node-modules # + symlink node_modules
#                                                     # from main (skips install)
#   source .env.worktree
#
# --link-node-modules: if the worktree's pnpm-lock.yaml and package.json
# match main's byte-for-byte, creates `node_modules` as a symlink to main's
# tree. Refuses (and tells you to run `pnpm install`) when they diverge,
# because running with a stale tree silently uses wrong dep versions.
#
# Run from the root of a worktree (not the main checkout). Safe to re-run:
# the same branch name always produces the same offset.
#
set -euo pipefail

LINK_NODE_MODULES=0
for arg in "$@"; do
  case "$arg" in
    --link-node-modules) LINK_NODE_MODULES=1 ;;
    -h|--help)
      sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$ROOT_DIR"

# In a worktree, .git is a FILE pointing at the worktree's gitdir.
# In the main checkout, .git is a directory. Skip bootstrap in main.
if [ -d ".git" ]; then
  echo "This is the main checkout — no bootstrap needed (offset stays at 0)."
  exit 0
fi

if [ ! -f ".git" ]; then
  echo "Not a git repository. Run from the root of a worktree." >&2
  exit 1
fi

branch="$(git rev-parse --abbrev-ref HEAD)"

# Deterministic offset derived from branch name.
# Range: 10..5000 in steps of 10, away from the default ports at offset 0.
# 500 slots keeps birthday collisions rare (~28 branches to 50% collision).
hash="$(printf '%s' "$branch" | cksum | awk '{print $1}')"
offset=$(( (hash % 500) * 10 + 10 ))

if [ ! -f ".env.dev" ]; then
  echo "Missing .env.dev — expected to be committed. Re-check your worktree." >&2
  exit 1
fi

cat > .env.worktree <<EOF
# Generated by tools/bootstrap-worktree.sh for branch: $branch
# Source this before running integration tests or dev servers:
#   source .env.worktree
export EMULATOR_PORT_OFFSET=$offset
export NEXT_PUBLIC_FUNCTIONS_EMULATOR_PORT=$((5001 + offset))
export NX_DAEMON=false
EOF

cat <<EOF
Worktree bootstrapped for branch '$branch'.

  EMULATOR_PORT_OFFSET=$offset
  functions: $((5001 + offset))   firestore: $((8080 + offset))
  auth:      $((9099 + offset))   ui:        $((4000 + offset))
  mock:      $((9999 + offset))

Load into your shell:
  source .env.worktree
EOF

# ---------------------------------------------------------------------------
# Optional: symlink node_modules from main checkout
# ---------------------------------------------------------------------------
if [ "$LINK_NODE_MODULES" = "1" ]; then
  # `.git` in a worktree is: "gitdir: <abs path to main/.git/worktrees/<name>>"
  # Resolve main's working tree from the common git dir.
  common_git_dir="$(git rev-parse --git-common-dir)"
  main_root="$(cd "$common_git_dir/.." && pwd)"

  if [ "$main_root" = "$ROOT_DIR" ]; then
    echo "Already in the main checkout — nothing to link." >&2
    exit 0
  fi

  if [ ! -d "$main_root/node_modules" ]; then
    echo "Main checkout has no node_modules at $main_root. Run 'pnpm install' there first." >&2
    exit 1
  fi

  # Lockfile + package.json must match byte-for-byte. Different deps means
  # the symlinked tree is wrong, and users would run stale versions silently.
  for f in pnpm-lock.yaml package.json pnpm-workspace.yaml; do
    if ! cmp -s "$main_root/$f" "$ROOT_DIR/$f"; then
      echo "" >&2
      echo "Cannot link node_modules: $f differs from main checkout." >&2
      echo "Run 'pnpm install --frozen-lockfile' in this worktree instead." >&2
      exit 1
    fi
  done

  if [ -d node_modules ] && [ ! -L node_modules ]; then
    echo "" >&2
    echo "Refusing to replace existing node_modules directory with a symlink." >&2
    echo "Remove it first: rm -rf node_modules" >&2
    exit 1
  fi

  rm -f node_modules
  ln -s "$main_root/node_modules" node_modules
  echo ""
  echo "Linked node_modules -> $main_root/node_modules"
  echo "(Re-run bootstrap or 'pnpm install' here if you change deps.)"
fi
