#!/usr/bin/env bash
#
# Run integration tests against Firebase emulators + mock HTTP server.
#
# Usage:
#   ./tools/run-integration-tests.sh              # run all suites
#   ./tools/run-integration-tests.sh square       # run one suite
#   ./tools/run-integration-tests.sh class square  # run multiple suites
#
# Port isolation for parallel worktrees:
#   EMULATOR_PORT_OFFSET=10 ./tools/run-integration-tests.sh
#   Shifts every port (functions, firestore, auth, ui, mock server) by N.
#   Source .env.worktree (generated by tools/bootstrap-worktree.sh) to set
#   a stable per-branch offset automatically.
#
# Prerequisites: pnpm, Java 21+ (for Firestore emulator)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$ROOT_DIR"

OFFSET="${EMULATOR_PORT_OFFSET:-0}"
FUNCTIONS_PORT=$((5001 + OFFSET))
FIRESTORE_PORT=$((8080 + OFFSET))
AUTH_PORT=$((9099 + OFFSET))
UI_PORT=$((4000 + OFFSET))
MOCK_SERVER_PORT=$((9999 + OFFSET))
ETSY_MOCK_SERVER_PORT=$((9998 + OFFSET))

if [ "$OFFSET" != "0" ]; then
  echo "Using EMULATOR_PORT_OFFSET=$OFFSET -> functions:$FUNCTIONS_PORT, firestore:$FIRESTORE_PORT, auth:$AUTH_PORT, ui:$UI_PORT, mock:$MOCK_SERVER_PORT, etsy-mock:$ETSY_MOCK_SERVER_PORT"
fi

# ---------------------------------------------------------------------------
# 1. Kill stale processes on OUR ports only (leave other worktrees alone)
# ---------------------------------------------------------------------------
for port in "$MOCK_SERVER_PORT" "$ETSY_MOCK_SERVER_PORT" "$FUNCTIONS_PORT" "$FIRESTORE_PORT" "$AUTH_PORT" "$UI_PORT"; do
  lsof -ti:"$port" 2>/dev/null | xargs kill -9 2>/dev/null || true
done
sleep 1

# ---------------------------------------------------------------------------
# 2. Build all function codebases (reset cache to avoid stale bundles)
# ---------------------------------------------------------------------------
echo "Building function codebases..."
pnpm exec nx reset 2>/dev/null || true
pnpm exec nx run functions:build
pnpm exec nx run functions-square:build
pnpm exec nx run functions-sync:build
pnpm exec nx run functions-calendar:build

# ---------------------------------------------------------------------------
# 3. Set up .env and .secret.local for every codebase
#
#    Firebase emulator requires ALL project-level params (defineString /
#    defineSecret) in every codebase's .env — even params that codebase
#    doesn't use. Missing params cause a silent hang (stdin prompt) in
#    non-interactive environments.
#
#    Solution: copy .env.dev everywhere, then append codebase-specific
#    overrides.
# ---------------------------------------------------------------------------
echo "Setting up emulator environment..."
for dir in dist/apps/functions dist/apps/functions-square dist/apps/functions-sync dist/apps/functions-calendar; do
  # Strip comments and blank lines — Firebase .env parser needs clean key=value pairs
  grep -v '^#' .env.dev | grep -v '^$' > "$dir/.env"
done

# maple-core: Etsy mock server URL + fake secrets (for listEtsyListings, getEtsyTemplates)
echo "ETSY_API_BASE=http://localhost:$ETSY_MOCK_SERVER_PORT/v3/application" >> dist/apps/functions/.env
printf "ETSY_API_KEY=fake\nETSY_SHARED_SECRET=fake\n" > dist/apps/functions/.secret.local

# maple-square: mock server URL + fake secrets
echo "SQUARE_BASE_URL=http://localhost:$MOCK_SERVER_PORT" >> dist/apps/functions-square/.env
echo "ETSY_API_BASE=http://localhost:$ETSY_MOCK_SERVER_PORT/v3/application" >> dist/apps/functions-square/.env
printf "SQUARE_ACCESS_TOKEN=mock-token\nSQUARE_WEBHOOK_SIGNATURE_KEY=mock-key\nETSY_API_KEY=fake\nETSY_SHARED_SECRET=fake\n" > dist/apps/functions-square/.secret.local

# maple-sync: mock server URL + fake secrets
echo "WEBFLOW_BASE_URL=http://localhost:$MOCK_SERVER_PORT" >> dist/apps/functions-sync/.env
echo "ETSY_API_BASE=http://localhost:$ETSY_MOCK_SERVER_PORT/v3/application" >> dist/apps/functions-sync/.env
echo "ETSY_TOKEN_URL=http://localhost:$ETSY_MOCK_SERVER_PORT/v3/public/oauth/token" >> dist/apps/functions-sync/.env
printf "WEBFLOW_API_TOKEN=mock-token\nETSY_API_KEY=fake\nETSY_SHARED_SECRET=fake\n" > dist/apps/functions-sync/.secret.local

# ---------------------------------------------------------------------------
# 4. Start mock HTTP servers (Square + Webflow + Etsy APIs)
# ---------------------------------------------------------------------------
echo "Starting monolithic mock server on :$MOCK_SERVER_PORT..."
MOCK_SERVER_PORT="$MOCK_SERVER_PORT" npx tsx libs/firebase/integration-test-mock-server/start.ts &
MOCK_PID=$!

echo "Starting Etsy mock server on :$ETSY_MOCK_SERVER_PORT..."
ETSY_MOCK_SERVER_PORT="$ETSY_MOCK_SERVER_PORT" npx tsx libs/firebase/etsy-test-mock-server/start.ts &
ETSY_MOCK_PID=$!
sleep 2

# ---------------------------------------------------------------------------
# 5. Pick a Firebase config (generate a port-shifted one if offset != 0)
# ---------------------------------------------------------------------------
FIREBASE_CONFIG_FILE="firebase.json"
if [ "$OFFSET" != "0" ]; then
  FIREBASE_CONFIG_FILE="firebase.worktree.json"
  node -e "
    const fs = require('fs');
    const cfg = JSON.parse(fs.readFileSync('firebase.json', 'utf8'));
    cfg.emulators.functions.port = $FUNCTIONS_PORT;
    cfg.emulators.firestore.port = $FIRESTORE_PORT;
    cfg.emulators.auth.port = $AUTH_PORT;
    cfg.emulators.ui.port = $UI_PORT;
    fs.writeFileSync('firebase.worktree.json', JSON.stringify(cfg, null, 2));
  "
fi

# ---------------------------------------------------------------------------
# 6. Run tests inside Firebase emulators
# ---------------------------------------------------------------------------
# Determine which test suites to run.
# Run vitest directly (not through the Nx executor) so assertion errors
# and stack traces are visible in the terminal output.
if [ $# -gt 0 ]; then
  TEST_CMD=""
  for suite in "$@"; do
    TEST_CMD="${TEST_CMD}pnpm exec vitest run --config apps/functions-integration-tests-${suite}/vitest.config.ts --reporter=verbose && "
  done
  # Remove trailing " && "
  TEST_CMD="${TEST_CMD% && }"
else
  TEST_CMD="node tools/run-integration-test-suites.js"
fi

echo "Running: $TEST_CMD"
EXIT_CODE=0
EMULATOR_PORT_OFFSET="$OFFSET" npx firebase --config "$FIREBASE_CONFIG_FILE" emulators:exec \
  --project=dev \
  --only auth,firestore,functions \
  "$TEST_CMD" || EXIT_CODE=$?

# ---------------------------------------------------------------------------
# 7. Cleanup
# ---------------------------------------------------------------------------
kill $MOCK_PID 2>/dev/null || true
kill $ETSY_MOCK_PID 2>/dev/null || true

if [ $EXIT_CODE -eq 0 ]; then
  echo ""
  echo "All integration tests passed."
else
  echo ""
  echo "Integration tests failed (exit code $EXIT_CODE)."
  echo ""
  echo "Tip: For verbose vitest output on a single suite, run:"
  echo "  npx vitest run --config apps/functions-integration-tests-<suite>/vitest.config.ts --reporter=verbose"
  echo "(while emulators + mock server are running)"
fi

exit $EXIT_CODE
